platform:
    - x86
    - x64

build_script:
    # VS2010 doesn't have a 64-bit install

    # VS2010
    - cmd: if "%PLATFORM%" == "x86" call "C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\vcvarsall.bat" %PLATFORM%
    - cmd: if "%PLATFORM%" == "x86" cl.exe -nologo -c lib\Remotery.c

    # VS2010 C++ mode
    - cmd: if "%PLATFORM%" == "x86" cl.exe -nologo -c -TP lib\Remotery.c

    # VS2010 OpenGL
    - cmd: if "%PLATFORM%" == "x86" cl.exe -nologo -c -DRMT_USE_OPENGL=1 lib\Remotery.c

    # VS2010 C++ mode OpenGL
    - cmd: if "%PLATFORM%" == "x86" cl.exe -nologo -c -TP -DRMT_USE_OPENGL=1 lib\Remotery.c

    # VS2010 D3D11
    - cmd: if "%PLATFORM%" == "x86" cl.exe -nologo -c -DRMT_USE_D3D11=1 lib\Remotery.c

    # VS2010 C++ mode D3D11
    - cmd: if "%PLATFORM%" == "x86" cl.exe -nologo -c -TP -DRMT_USE_D3D11=1 lib\Remotery.c

    # VS2015
    - cmd: call "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" %PLATFORM%
    - cmd: cl.exe -nologo -c lib\Remotery.c

    # VS2015 C++ mode
    - cmd: cl.exe -nologo -c -TP lib\Remotery.c    

    # VS2015 OpenGL
    - cmd: cl.exe -nologo -c -DRMT_USE_OPENGL=1 lib\Remotery.c

    # VS2015 C++ mode OpenGL
    - cmd: cl.exe -nologo -c -TP -DRMT_USE_OPENGL=1 lib\Remotery.c

    # VS2015 D3D11
    - cmd: cl.exe -nologo -c -DRMT_USE_D3D11=1 lib\Remotery.c

    # VS2015 C++ mode D3D11
    - cmd: cl.exe -nologo -c -TP -DRMT_USE_D3D11=1 lib\Remotery.c

